name: nip.io ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mock pytest assertpy black flake8 types-mock mypy
          pip install .
      - name: Linting
        run: |
          black --check --diff --color -q nipio nipio_tests setup.py
          flake8 nipio nipio_tests setup.py
          mypy nipio nipio_tests setup.py
      - name: Test with pytest
        run: |
          pytest --junitxml="result.xml"
      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: result.xml
          reporter: java-junit
